### ISSUE TITLE
Conflicting tests...

### ISSUE THREAD

**Issue by BilobedCarton** [DamienDumayas/a1p2#10]
These tests are failing rightfully, but I'm not sure if they're proper tests...
t_false(a4->get(0)->equals(a));
t_false(a4->get(1)->equals(b));
t_false(a4->get(2)->equals(a_obj));

They are followed by the reverse tests...
t_true(a4->get(0)->equals(a));
t_true(a4->get(1)->equals(b));
t_true(a4->get(2)->equals(a_obj));
t_true(a4->get(3)->equals(b));

**Comment by DamienDumayas** [comment]
https://github.com/DamienDumayas/a1p2/commit/41eeed2f0d484636aa804a83c048970027fd25ec

My bad. Removed those tests.
