### ISSUE TITLE
Question about specific test

### ISSUE THREAD

**Issue by dodecahedronal** [DamienDumayas/a1p2#12]
Could you explain the following test on line 52
```
       t_false(a1_str->get(0) == a);
```

Shouldn't this be t_true?

**Comment by dodecahedronal** [comment]
Also, on line 71
```
t_true(a3->index(a_obj) == 2);
```

Since the contents of a3 are {a, b, a}, shouldn't the index found for a_obj, which is a, be 0? How would you get to the third element? So shouldn't this be t_false?

**Comment by DamienDumayas** [comment]
yeah. Let me change it

**Comment by DamienDumayas** [comment]
nevermind. it was commented out
