### ISSUE TITLE
test-array.cpp

### ISSUE THREAD

**Issue by dodecahedronal** [DamienDumayas/a1p2#5]
In your test-array.cpp (line 133), there’s a test comparing an array to its reverse. Shouldn’t it look like: 

~~~~
for (size_t i = 0; i < a7->count(); i++) {

        t_true(a7->get(i)->equals(temp_a->get(a7->count() - i-1)));

}
~~~~

Because otherwise, let’s say i=0, you’d be comparing the 0 index element of the array with the count-i = 3-0 = 3, so the element with index 3 of the other array. But the index starts from 0, so you’d want to compare with the element at index 2, not 3.

**Comment by DamienDumayas** [comment]
Thanks for catch
