### ISSUE TITLE
Testing pointer equality without cast

### ISSUE THREAD

**Issue by BilobedCarton** [DamienDumayas/a1p2#6]
test: line 57
t_false(a1_str->get(0) == a);

Hi you are testing pointer equality without casting the returned object from get() and the test is failing. There are likely other instances of this kind of pointer comparison that should get fixed as well.

Our suggested edit is:
t_false(((String*)a1_str->get(0)) == a);

**Comment by DamienDumayas** [comment]
That test shows that memory addresses are different (they should be copies).

However, based on the current tests with Array and the primitive arrays equals method will not work on primitives so there are two fixes I can do (or you can suggest please):

1. Change the signature to add, remove and get references instead of copies of the items.
2. Make a separate generic test for primitive arrays that uses ==.

**Comment by BilobedCarton** [comment]
Yeah let's do references!
Thanks!

**Comment by BilobedCarton** [comment]
Okay, I took a look. So technically templates are not allowed in CwC. I think it might be a better idea with CwC to have separate tests for primitive arrays...
Otherwise, we're getting a number of errors on compile that ints are not pointers. I think you're treating primitives like Objects and that's not valid.

**Comment by BilobedCarton** [comment]
^ that might be on our end though. I'll get back to you.

**Comment by BilobedCarton** [comment]
Also, if we're copying the objects we want to put in the array, can you provide a copy method in the object class?

**Comment by DamienDumayas** [comment]
Tests can be written in C++ and Array must be written in CwC. Cool Can you change the signature and the tests to use == instead of ->equals(..)? I got class right now. I put a copy constructor in String but since you want references you won't need it.

**Comment by BilobedCarton** [comment]
The signature for append says we add a copy of the object, so we need a object copy constructor as well. I'm gonna fork and open a pr with my proposed changes.

**Comment by DamienDumayas** [comment]
Just assume everything is a reference instead of a copy. I will change it after class

**Comment by BilobedCarton** [comment]
Nah we can do copy, don't worry! It's in my pr.
